#!/bin/bash

CHOICE=$(zenity --list \
    --height=220 \
    --width=250 \
    --title="Kramden Customization" \
    --text="Choose Station" \
    --radiolist \
    --column="" --column="Station" \
    FALSE "OS Load" \
    TRUE "Final Test")

case $CHOICE in
    "OS Load")
        echo "OS Load"
	./osload
    ;;
    "Final Test")
        echo "Final Test"
	./finaltest
    ;;
esac
