#!/bin/bash

failed=0
error_text=""

who=`whoami`
if [ "$who" != "owner" ];
then
    failed=1
    error_text="$error_text <span><b>Username:</b> $who</span>
"
fi

for p in org.videolan.VLC com.anydesk.Anydesk net.sourceforge.Klavaro us.zoom.Zoom com.google.Chrome;
do
  flatpak info $p > /dev/null 2>&1
  if [ $? -ne 0 ];
  then
    failed=1
    error_text="$error_text <span><b>$p not installed</b></span>
"
  fi
done

bg_string='file://'$HOME'/Pictures/Wallpapers/Background-Endless.png'
current_background=`gsettings get org.gnome.desktop.background picture-uri | tr -d "'"`
if [ "$current_background" != $bg_string ];
then
    failed=1
    error_text="$error_text <span><b>Current Background:</b> $current_background</span>
"
fi
local_bg_file=`echo $current_background | sed -e 's/file:\/\///g'`

if [ ! -f $local_bg_file ];
then
    failed=1
    echo "$local_bg_file doesn't exist"
    error_text="$error_text <span><b>Background image doesn't exist:</b> $current_background</span>
"
fi

icon_file=`gdbus introspect --system --dest org.freedesktop.Accounts --object-path /org/freedesktop/Accounts/User1000 --only-properties  |grep IconFile | sed -e 's/readonly s IconFile = //g'|tr -d ';'|tr -d ' '| tr -d "'"`

if [ ! $icon_file = "/usr/share/icons/Adwaita/48x48/status/avatar-default.png" ] && [ ! "$icon_file" = "$HOME/.face" ];
then
    failed=1
    echo "$icon_file should be /usr/share/icons/Adwaita/48x48/status/avatar-default.png"
    error_text="$error_text <span><b>Icon File:</b> $icon_file</span>
"
fi

auto_login=`gdbus introspect --system --dest org.freedesktop.Accounts --object-path /org/freedesktop/Accounts/User1000 --only-properties  |grep AutomaticLogin | sed -e 's/readonly b AutomaticLogin = //g'|tr -d ';'|tr -d ' '| tr -d "'"`
if [ $auto_login != 'true' ];
then
    failed=1
    echo "Automatic Login set to $auto_login"
    error_text="$error_text <span><b>Automatic Login:</b> $auto_login</span>
"
fi



lo_setup_failed=0
grep com.sun.star.text.TextDocument \
    $HOME/.var/app/org.libreoffice.LibreOffice/config/libreoffice/*/user/registrymodifications.xcu 2>/dev/null | \
    grep -q "MS Word 2007"
if [ $? -ne 0 ];
then
    lo_setup_failed=1
fi

grep com.sun.star.presentation.PresentationDocument \
    $HOME/.var/app/org.libreoffice.LibreOffice/config/libreoffice/*/user/registrymodifications.xcu 2>/dev/null | \
if [ $? -ne 0 ];
then
    lo_setup_failed=1
fi
grep com.sun.star.sheet.SpreadsheetDocument \
    $HOME/.var/app/org.libreoffice.LibreOffice/config/libreoffice/*/user/registrymodifications.xcu 2>/dev/null | \
    grep -q "MS Excel 2007 XML"
if [ $? -ne 0 ];
then
    lo_setup_failed=1
fi
if [ $lo_setup_failed -eq 1 ];
then
    failed=1
    error_text="$error_text <span><b>LibreOffice not configured</b></span>
"
fi



#upower -e|grep battery > /dev/null
#if [ $? -eq 0 ];
#then
#  battery_check=`./battery`
#  if [ $? -ne 0 ];
#  then
#    failed=1
#    error_text="$error_text $battery_check"
#  fi
#fi

if [ $failed -eq 1 ];
then
    zenity --error --no-wrap --width=200 --title "Kramden Customization" --text="$error_text"
else
    zenity --info --no-wrap --width=200 --title "Kramden Customization" --text="Final Test Pass"
fi
