#!/usr/bin/sh

mkdir -p $HOME/Pictures/Wallpapers

cp -p Background-Endless.png $HOME/Pictures/Wallpapers/
cp -rp skel/.var $HOME/

bg_string='file://'$HOME'/Pictures/Wallpapers/Background-Endless.png'

gsettings set org.gnome.desktop.background picture-uri $bg_string

cp -rp skel/.local/share/desktop-directories $HOME/.local/share/

gdbus call --system --dest org.freedesktop.Accounts --object-path /org/freedesktop/Accounts/User1000 -m org.freedesktop.Accounts.User.SetIconFile '/usr/share/icons/Adwaita/48x48/status/avatar-default.png'

gdbus call --system --dest org.freedesktop.Accounts --object-path /org/freedesktop/Accounts/User1000 -m org.freedesktop.Accounts.User.SetAutomaticLogin true





gnome-software --quit




zenity --info --no-wrap --title "Kramden OS Customization" --text="Customization complete"

./finaltest
